services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev
    ports:
      - "5080:80"
      - "2525:25"
    restart: always

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "5090:8080"
    restart: always
    depends_on:
      - sql